version: "3"
services:
  rest-server:
    build: 
        dockerfile: dockers/todo-rest-server/Dockerfile
        context: ../
    ports:
     - "5000:5000"
  static-server:
    build: 
        dockerfile: dockers/todo-static-server/Dockerfile
        context: ../
    ports:
     - "8080:80"
